-- Création de la table pour les plannings
CREATE TABLE IF NOT EXISTS public.planning (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Colonnes spécifiques
    cond text,
    rec text,
    deriv text,
    signe text,
    sg text,
    cv text,
    python text,
    lim text,
    raph text, -- "Graph" dans Excel
    conv text,
    vect text,
    dte text,
    lim_fn text,
    co text,
    den text,
    trigo text,
    plan text,
    v text,
    bino text,
    integr text,
    aire text,
    int_plus text, -- Pour "Int+<"
    va text,
    ed text
);

-- Création de la table pour les notes (Trimestres 1, 2, 3)
CREATE TABLE IF NOT EXISTS public.eleves (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    trimestre text not null, -- 'T1', 'T2', 'T3'
    
    nom text,
    prenom text,
    moyenne numeric,
    qcm numeric,
    regularite numeric,
    brique_ib numeric,
    brique_plus numeric,
    total_briques numeric,
    apprentissage numeric,
    dst numeric,
    bb numeric,
    moy_dst numeric
);

-- Activer Row Level Security (RLS) pour la sécurité (optionnel mais recommandé)
ALTER TABLE public.planning ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eleves ENABLE ROW LEVEL SECURITY;

-- Créer une politique permettant l'accès public (lecture/écriture) pour simplifier le test
-- ATTENTION : Pour la production, restreindre l'accès
CREATE POLICY "Enable all for anon" ON public.planning
FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Enable all for anon" ON public.eleves
FOR ALL USING (true) WITH CHECK (true);
